"""empty message

Revision ID: 633b8c1e56df
Revises: e6b886534447
Create Date: 2021-05-21 13:40:34.634832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '633b8c1e56df'
down_revision = 'e6b886534447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('latitude', sa.String(length=120), nullable=True))
    op.add_column('address', sa.Column('longtitude', sa.String(length=120), nullable=True))
    op.drop_column('address', 'coords')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('coords', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('address', 'longtitude')
    op.drop_column('address', 'latitude')
    # ### end Alembic commands ###
