"""empty message

Revision ID: f5b756ab51b6
Revises: 
Create Date: 2021-05-20 12:32:32.619806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5b756ab51b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('product_id', sa.Integer(), nullable=False))
    op.drop_constraint('images_ibfk_1', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'farmer', ['product_id'], ['id'])
    op.drop_column('images', 'farmer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('farmer_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_ibfk_1', 'images', 'farmer', ['farmer_id'], ['id'])
    op.drop_column('images', 'product_id')
    # ### end Alembic commands ###
